---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  hosts: test-kitchen
  ansible_verbose: true
  ansible_verbosity: 1
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  # idempotency_test: true

verifier:
  name: inspec

platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6.7
- name: centos-7.2

suites:
- name: default
